<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // getUser ==> returns a promise object when resolved returns an array of objects{id: 1, name:John, age:25}, {id: 2, name:Emily, age:20}, id: 3, name:Michael, age:20 after 5 sec
        function getUser() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    const userInfo = [{ id: 1, name: 'John', age: 25 }, { id: 2, name: 'Emily', age: 20 }, { id: 3, name: 'Michael', age: 20 }]

                    if(userInfo.length > 1)resolve(userInfo)
                    else reject("There was an error")
                }, 5000)
            })
        }

        // function showarray() {
        //     return new Promise((resolve, reject) => {
        //         const obj = [{ id: 1, name: "a" }, { id: 2, name: "b" }];
        //         const showarr = true;

        //         setTimeout(() => {
        //             if (showarr) {
        //                 console.log(obj)
        //                 resolve(obj);

        //             }
        //             else {
        //                 reject("An error occurred");
        //             }
        //         }, 5000);
        //     });
        // }
        function findUser(obj, id) {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    const found = obj.find((item) => item.id === id);
                    if (found) {
                        resolve(found.name);
                    } else {
                        reject("id not found");
                    }
                }, 2000);
            })

        }
        async function handle() {
            try {
                const o = await getUser();
                const user = await findUser(o, 1);
                console.log(user);
            } catch (error) {
                console.error("An error occurred:", error);
            }
        }

        handle();
    </script>
</body>

</html>